# Development/Testing Override for OSINT Setup
# Use: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up

version: '3.8'

services:
  open-webui:
    environment:
      # Development settings
      LOG_LEVEL: "DEBUG"
      WEBUI_AUTH: "false"  # Disable auth for testing
      ENABLE_SIGNUP: "true"
      
      # Enable additional debugging
      RAG_EMBEDDING_ENGINE_DEBUG: "true"
      WEBUI_DEBUG: "true"
      
      # Test with localhost Ollama if available (fallback option)
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
    
    # Enable development port
    ports:
      - "3000:8080"  # Main port
      - "3001:8081"  # Debug port (if available)

  open-webui-searxng:
    # Expose SearXNG for direct testing
    ports:
      - "8080:8080"
    environment:
      # Enable debug logging for OSINT engine testing
      - SEARXNG_DEBUG=1

  open-webui-tika:
    # Expose Tika for direct testing
    ports:
      - "9998:9998"

  open-webui-litellm:
    environment:
      # Enable debug mode
      LITELLM_LOG: "DEBUG"
      # Test with both external and host-based Ollama
      OLLAMA_HOST_FALLBACK: "http://host.docker.internal:11434"
    
    # Expose LiteLLM for direct access
    ports:
      - "4000:4000"
