# OSINT-Optimized SearXNG Configuration Template
# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "your-searxng-secret-key-change-me"
  limiter: true
  image_proxy: true
  method: "POST"  # More private than GET requests
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: "1; mode=block"
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer
  Cache-Control: no-store

ui:
  static_use_hash: true
  default_locale: "en"
  query_in_title: false  # Don't expose search terms in title
  infinite_scroll: false
  center_alignment: false
  cache_url: "https://web.archive.org/web/"

redis:
  url: redis://open-webui-redis:6379/0

valkey:
  url: redis://open-webui-redis:6379/0

search:
  # Privacy-focused search settings for OSINT
  safe_search: 0  # No filtering for comprehensive OSINT results
  autocomplete: ""  # Disable autocomplete for privacy
  default_lang: "all"
  # be polite but persistent
  ban_time_on_fail: 15
  max_ban_time_on_fail: 900
  suspended_times:
    SearxEngineAccessDenied: 86400
    SearxEngineCaptcha: 86400
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 86400
    cf_SearxEngineAccessDenied: 86400
  # concurrency/timeout knobs
  max_bang_count: 3
  request_timeout: 8.0
  max_request_timeout: 12.0
  formats:
    - html
    - json
    - csv
    - rss

# OSINT-focused engines configuration — rely on defaults when enabled above
